# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://skyiptv.github.io
date_format: "ordinal"
title: SKY IPTV
subtitle: “Best China IPTV Service Provider”
description: “IPTV Box, Android TV Box, Subscription, SKY IPTV Pro, SKY IPTV Pro+"
keywords: SKY IPTV, Android TV Box, Subscription
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: SKY IPTV
organization: SKY IPTV
organization_url: https://www.skyiptv.club
location: Shanghai, China
email: info@skyiptv.club

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: skyiptv/skyiptv.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: skyiptv
douban_username: XXXX
facebook_username: sky.iptv.cn
weibo_username: XXXX
zhihu_username: XXXX
twitter_username: skyiptvcn

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
# comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
## disqus:
##    username: XXX
# 在使用 disqus 的时候可点击显示多说评论框

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id:

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [SKY, SKY IPTV, TV Box, Android, Live TV, TV Channels]
